overlay = "."
crate_src_path = ".."
whitelist = ["tests/*.c"]

maintainer = "Proxmox Support Team <support@proxmox.com>"

[source]
vcs_git = "git://git.proxmox.com/git/proxmox-backup.git"
vcs_browser = "https://git.proxmox.com/?p=proxmox-backup.git;a=summary"
section = "admin"
build_depends = [
  "bash-completion",
  "debhelper (>= 12~)",
  "fonts-dejavu-core <!nodoc>",
  "fonts-lato <!nodoc>",
  "fonts-open-sans <!nodoc>",
  "graphviz <!nodoc>",
  "latexmk <!nodoc>",
  "patchelf",
  "proxmox-widget-toolkit-dev <!nodoc>",
  "pve-eslint (>= 7.18.0-1)",
  "python3-docutils",
  "python3-pygments",
  "python3-sphinx <!nodoc>",
  "rsync",
  "texlive-fonts-extra <!nodoc>",
  "texlive-fonts-recommended <!nodoc>",
  "texlive-xetex <!nodoc>",
  "xindy <!nodoc>",
]

build_depends_excludes = [
  "debhelper (>=11)",
]

[packages.lib]
depends = [
  "libacl1-dev",
  "libfuse3-dev",
  "libsystemd-dev",
  "uuid-dev",
  "libsgutils2-dev",
]
