[package]
name = "pbs-buildcfg"
version = "2.0.14"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
description = "macros used for pbs related paths such as configdir and rundir"
build = "build.rs"

[dependencies]
