[package]
name = "pbs-api-types"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
description = "general API type helpers for PBS"

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
libc = "0.2"
nix = "0.19.1"
openssl = "0.10"
regex = "1.2"
serde = { version = "1.0", features = ["derive"] }

proxmox = { version = "0.12.0", default-features = false, features = [ "api-macro" ] }

pbs-systemd = { path = "../pbs-systemd" }
pbs-tools = { path = "../pbs-tools" }
