[package]
name = "pbs-ticket"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "pbs ticket handling"

[dependencies]
anyhow.workspace = true
base64.workspace = true
openssl.workspace = true
percent-encoding.workspace = true

proxmox-time.workspace = true
